### ISSUE TITLE
Make menu-button light notifications lighter.

### ISSUE THREAD

**Issue by kubaork** [ksiazkowicz/lightbulb#28]
I can't see when my menu button is blinking in day I can only see it in night :/. When I have for example SMS, this is blinking lighter so this must be a problem in your application.
Device: N8, "Notification LED: 4"

**Comment by ghost** [comment]
I am also having the same problem. Device: nokia 603 belle fp2 OFW

**Comment by ksiazkowicz** [comment]
The API allows me to access menu key light, trying to use notification LED itself causes app to hang or simply crash. Maybe it's a matter of capabilities. That's why using Delight CFW or more precisely the mod to disable menu key light breaks this feature.

I'm not sure if there is any way to fix this issue, sorry.
