### ISSUE TITLE
Lag switching between chats or going back to online list (fb)

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#37]
Hi Pizarz, 
I have been testing about what you said:

 "I noticed having lots of messages in a chat could cause a delay when going into chat, switching between chats and going back"

I `ve discovered that having a lot of mesages doesnt cause  the lag(freezing screen), it lags anyway, if you have 1 or 2 messages the lagg may appear, and if you have a lot of them, it may not.

I dont know how to realize what may be the problem, do you have any idea or suggestion to test? Sorry for bothering because of this issue, but if you receive something it delays the functionalities and answers :D

PD: I tried hangout but I dont  even know  how to add contacts haha. skype facebook whatsapp?

**Comment by ksiazkowicz** [comment]
I still think it must be because conversation view is heavy as hell. Moving the resource switcher out of it to a separate file (bug #26) would probably make it load/unload faster.

Facebook sucks and I already have a shitload of people I don't know there. Skype - ok, look for pisarz.ksiazkowicz, but text only. WhatsApp - I don't use it.

**Comment by ksiazkowicz** [comment]
So apparently this issue was fixed in Fluorescent. I'm closing it now.
