### ISSUE TITLE
LED notification

### ISSUE THREAD

**Issue by jara001** [ksiazkowicz/lightbulb#62]
Hello,
LED notification test seems to have a bug or something. It doesn't work and if I press "try again" button, whole screen goes black and phone stops reacting to everything (at least it looks like this). Only solution is to remove battery and reinstall whole app.
Can you make those "try again" tests like 5 sec long? It could help me set notifications and also stop bricking my phone. :P

Thanks a lot for this app and for you reply, Jara

**Comment by ksiazkowicz** [comment]
That's actually weird. This issue is known to happen when user is trying to use the same target that is used internally for notification LED. "Try again" actually just makes it switch between targets.

Are you using 0.4 or 0.3.1? If you could provide me "[notifications]" section from Settings.conf, I'd be glad.
0.3.1: X:\private\e22ac278\Settings.conf
0.4: X:\private\e00ac666\Settings.conf
0.3 and older: C:\data.config\Lightbulb\Lightbulb.conf
Where X means the drive you installed it on.

I'd also like to know what device are you using, which firmware and is it hacked.

**Comment by jara001** [comment]
I'm using latest 0.4 on my hacked 603 (RM-779, 113.010.1506).
Here's the part of conf file: http://pastebin.com/prZZgC22 (Why I can't simply paste it here? )

**Comment by ksiazkowicz** [comment]
Could you change blinkScreenDevice to 4 and see what happens?

**Comment by jara001** [comment]
When I recieve message screen goes black. If I dbl press lock button, screen flashes (1x). But it seems like device is still working even without active screen. (I managed to turn off app, relock device and it's all working again)

**Comment by ksiazkowicz** [comment]
So apparently, using ECustomTarget4 on 603 might cause this issue. Try setting it to 2 if 1 doesn't work (I guess that's why you tapped on "try again"), 3 might probably cause your phone to hang if I recall correctly.

I'll try to find a workaround for this issue.

**Comment by jara001** [comment]
After I found that out, only one thing crossed my mind: "You are going to kill me. :smiley: ". I was just hanging around with my friends and saw that LED flashing (I know that it's not very bright, but this?) So result is: LED is flashing the whole time :( 
Still, there is (or was?) problem with switching LED access thing, that made my phone go crazy. 

I'm sorry I didn't write sooner, but I was out of civilization. 

J.

**Comment by ksiazkowicz** [comment]
I don't really get your issue but if you're still having it, let me know.
